### ISSUE TITLE
IoT Agent get stuck if mongodb is not ready

### ISSUE THREAD

**Issue by ericbaum** [dojot/iotagent-json#3]
When starting the IoT Agent, if the Mongo DB was unreachable for whatever reason the IoT Agent reaches a state where it gets stuck.

When the mongo db is within range, nothing changes and the IoT Agent remains on that idle state from where it never recovers.

**Comment by mmagr** [comment]
After #4 iotagent will no longer rely on mongodb to function.

**Comment by giovannicuriel** [comment]
Can we close this issue?

**Comment by giovannicuriel** [comment]
Hi.

**Comment by ericbaum** [comment]
I guess so.
